/obj/structure/retail/costume_store
	desc = "Purchase a mask for that ugly mug."
	products_list = list(
		new /datum/data/vending_product("balaclava", /obj/item/clothing/mask/vampire/balaclava, 10),
		new /datum/data/vending_product("bear mask", /obj/item/clothing/mask/animal/small/bear, 13),
		new /datum/data/vending_product("rat mask", /obj/item/clothing/mask/animal/small/rat, 10),
		new /datum/data/vending_product("bee mask", /obj/item/clothing/mask/animal/small/bee, 12),
		new /datum/data/vending_product("fox mask", /obj/item/clothing/mask/animal/small/fox, 10),
		new /datum/data/vending_product("bat mask", /obj/item/clothing/mask/animal/small/bat, 15),
		new /datum/data/vending_product("raven mask", /obj/item/clothing/mask/animal/small/raven, 20),
		new /datum/data/vending_product("jackal mask", /obj/item/clothing/mask/animal/small/jackal, 20),
		new /datum/data/vending_product("medical mask", /obj/item/clothing/mask/surgical, 10),
		new /datum/data/vending_product("mummy mask", /obj/item/clothing/mask/mummy, 15),
		new /datum/data/vending_product("scarecrow mask", /obj/item/clothing/mask/scarecrow, 10),
		new /datum/data/vending_product("respirator", /obj/item/clothing/mask/gas/vampire),
		new /datum/data/vending_product("black and gold luchador mask", /obj/item/clothing/mask/luchador, 10),
		new /datum/data/vending_product("green luchador mask", /obj/item/clothing/mask/luchador/tecnicos, 10),
		new /datum/data/vending_product("red and blue luchador mask", /obj/item/clothing/mask/luchador/rudos, 10),
		new /datum/data/vending_product("Venetian mask", /obj/item/clothing/mask/vampire/venetian_mask, 30),
		new /datum/data/vending_product("fancy Venetian mask", /obj/item/clothing/mask/vampire/venetian_mask/fancy, 200),
		new /datum/data/vending_product("jester mask", /obj/item/clothing/mask/vampire/venetian_mask/jester, 50),
		new /datum/data/vending_product("bloody mask", /obj/item/clothing/mask/vampire/venetian_mask/scary, 30),
		new /datum/data/vending_product("comedy mask", /obj/item/clothing/mask/vampire/comedy, 25),
		new /datum/data/vending_product("tragedy mask", /obj/item/clothing/mask/vampire/tragedy, 25),
		new /datum/data/vending_product("shemagh", /obj/item/clothing/mask/vampire/shemagh, 20),
	)
