/obj/structure/retail/flower_shop
	desc = "The only 24hr flower shop in SanFran."
	products_list = list(
		new /datum/data/vending_product("Gardening Gloves", /obj/item/clothing/gloves/botanic_leather, 45),
		new /datum/data/vending_product("respirator", /obj/item/clothing/mask/gas/vampire),
		new /datum/data/vending_product("Plant Bag", /obj/item/storage/bag/plants, 45),
		new /datum/data/vending_product("Basic Fertilizer", /obj/item/reagent_containers/cup/bottle/nutrient/ez, 100),
		new /datum/data/vending_product("Herbicide", /obj/item/reagent_containers/spray/weedspray, 25),
		new /datum/data/vending_product("Pesticide", /obj/item/reagent_containers/spray/pestspray, 25),
		new /datum/data/vending_product("Spade", /obj/item/shovel/spade, 100),
		new /datum/data/vending_product("Wooden Bucket", /obj/item/reagent_containers/cup/bucket/wooden, 100),
		new /datum/data/vending_product("Secateurs", /obj/item/secateurs, 100),
		new /datum/data/vending_product("Garden Rake", /obj/item/cultivator/rake, 100),
		new /datum/data/vending_product("Cultivator", /obj/item/cultivator, 100),
		new /datum/data/vending_product("Poppy seeds", /obj/item/seeds/poppy, 50),
		new /datum/data/vending_product("Sunflower seeds", /obj/item/seeds/sunflower, 50),
		new /datum/data/vending_product("Geranium seeds", /obj/item/seeds/poppy/geranium, 50),
		new /datum/data/vending_product("Lily seeds", /obj/item/seeds/poppy/lily, 50),
		//new /datum/data/vending_product("Forget me not seeds", /obj/item/seeds/forgetmenot, 50),
		new /datum/data/vending_product("Aloe seeds", /obj/item/seeds/aloe, 50),
		new /datum/data/vending_product("Apple seeds", /obj/item/seeds/apple, 50),
		new /datum/data/vending_product("Cabbage seeds", /obj/item/seeds/cabbage, 50),
		new /datum/data/vending_product("Carrot seeds", /obj/item/seeds/carrot, 50),
		new /datum/data/vending_product("Corn seeds", /obj/item/seeds/corn, 50),
		new /datum/data/vending_product("Oat seeds", /obj/item/seeds/wheat/oat, 50),
		new /datum/data/vending_product("Onion seeds", /obj/item/seeds/onion, 50),
		new /datum/data/vending_product("Parsnip seeds", /obj/item/seeds/carrot/parsnip, 50),
		new /datum/data/vending_product("Peas seeds", /obj/item/seeds/peas, 50),
		new /datum/data/vending_product("Potato seeds", /obj/item/seeds/potato, 50),
		new /datum/data/vending_product("Pumpkin seeds", /obj/item/seeds/pumpkin, 50),
		new /datum/data/vending_product("Rice seeds", /obj/item/seeds/wheat/rice, 50),
		new /datum/data/vending_product("Soy seeds", /obj/item/seeds/soya, 50),
		new /datum/data/vending_product("Tomato seeds", /obj/item/seeds/tomato, 50),
		new /datum/data/vending_product("Fermentation Barrel", /obj/structure/fermenting_barrel, 230),
		new /datum/data/vending_product("Soil sack", /obj/item/soil_sack),
		new /datum/data/vending_product("Rich soil sack", /obj/item/soil_sack/rich),
		)
