/obj/structure/retail/gun_store
	desc = "Boom! Booom!! BOOOOOOM!!!!"
	products_list = list(
		new /datum/data/vending_product("magnum revolver", /obj/item/gun/ballistic/revolver/darkpack/magnum, 200),
		new /datum/data/vending_product("Colt M1911", /obj/item/gun/ballistic/automatic/pistol/darkpack/m1911, 250),
		new /datum/data/vending_product("Elite 92G", /obj/item/gun/ballistic/automatic/pistol/darkpack/beretta, 500),
		new /datum/data/vending_product("desert eagle", /obj/item/gun/ballistic/automatic/pistol/darkpack/deagle, 600),
		new /datum/data/vending_product("lever action rifle", /obj/item/gun/ballistic/rifle/darkpack/lever, 1600),
		new /datum/data/vending_product("hunting rifle", /obj/item/gun/ballistic/automatic/darkpack/huntrifle, 2000),
		new	/datum/data/vending_product("5.45 ammo", /obj/item/ammo_box/darkpack/c545, 1000),
		new	/datum/data/vending_product(".45 ammo", /obj/item/ammo_box/darkpack/c45acp, 700),
		new /datum/data/vending_product("9mm ammo", /obj/item/ammo_box/darkpack/c9mm, 600),
		new /datum/data/vending_product(".44 ammo", /obj/item/ammo_box/darkpack/c44, 800),
		new /datum/data/vending_product("5.56 ammo", /obj/item/ammo_box/darkpack/c556, 2000),
		new /datum/data/vending_product("shotgun", /obj/item/gun/ballistic/shotgun/vampire, 900),
		new /datum/data/vending_product("double barrel shotgun", /obj/item/gun/ballistic/shotgun/vampire/doublebarrel, 1100),
		new /datum/data/vending_product("12ga shotgun shells, buckshot", /obj/item/ammo_box/darkpack/c12g/buck, 400),
		new /datum/data/vending_product("desert eagle magazine", /obj/item/ammo_box/magazine/m44, 100),
		new /datum/data/vending_product("hunting rifle magazine, 5.56", /obj/item/ammo_box/magazine/darkpack556/hunt, 200),
		new /datum/data/vending_product("9mm pistol magazine, 18 rounds", /obj/item/ammo_box/magazine/semi9mm, 100),
		new /datum/data/vending_product("Colt M1911 magazine", /obj/item/ammo_box/magazine/darkpack45acp, 50),
		new /datum/data/vending_product("knife", /obj/item/knife/vamp, 100),
		new /datum/data/vending_product("baseball bat", /obj/item/melee/baseball_bat/vamp, 200),
		new /datum/data/vending_product("real katana", /obj/item/katana/vamp, 1500),
		new /datum/data/vending_product("machete", /obj/item/claymore/machete, 500),
		new /datum/data/vending_product("taser", /obj/item/melee/baton/security/handtaser, 250),
		new /datum/data/vending_product("pepperspray", /obj/item/reagent_containers/spray/pepper, 200),
	)
